block_cipher = None

a = Analysis(
    ['backend/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('frontend/dist',                   'frontend/dist'),
        ('backend/models.py',               'backend'),
        ('backend/config.py',               'backend'),
        ('backend/constants.py',            'backend'),
        ('backend/file_parser.py',          'backend'),
        ('backend/document_ingestion.py',   'backend'),
        ('backend/test_case_generator.py',  'backend'),
        ('backend/output_generator.py',     'backend'),
        ('backend/mcp_server.py',           'backend'),
        ('backend/mcp_client.py',           'backend'),
        ('backend/output_validator.py',      'backend'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.responses',
        'starlette.staticfiles',
        'pydantic',
        'pydantic.v1',
        'fitz',
        'docx',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'statistics',
        'difflib',
        'subprocess',
        'pathlib',
        'multipart',
        'python_multipart',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TestCaseGenerator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
)
